import { CardConfig } from "@/types";

export const cardConfig: CardConfig = {
  types: [
    { title: "JP", id: 1 },
    { title: "EN", id: 2 },
    { title: "ID", id: 3 },
    { title: "0期生", id: 4 },
    { title: "1期生", id: 5 },
    { title: "2期生", id: 6 },
    { title: "3期生", id: 7 },
    { title: "4期生", id: 8 },
    { title: "5期生", id: 9 },
    { title: "ID1期生", id: 10 },
    { title: "ID3期生", id: 11 },
    { title: "Promise", id: 12 },
    { title: "秘密結社holoX", id: 13 },
    { title: "歌", id: 14 },
    { title: "絵", id: 15 },
    { title: "トリ", id: 16 },
    { title: "ケモミミ", id: 17 },
    { title: "ハーフエルフ", id: 18 },
    { title: "お酒", id: 19 },
    { title: "海", id: 20 },
    { title: "Myth", id: 21 },
  ],
  rarity: [
    { title: "RR", id: 1 },
    { title: "R", id: 2 },
    { title: "U", id: 3 },
    { title: "C", id: 4 },
    { title: "OSR", id: 5 },
    { title: "OC", id: 6 },
    { title: "SEC", id: 7 },
    { title: "OUR", id: 8 },
    { title: "UR", id: 9 },
    { title: "P", id: 10 },
  ],
  colors: [
    { title: "白", id: 1, value: "#c0c0c0" },
    { title: "緑", id: 2, value: "#32cd32" },
    { title: "赤", id: 3, value: "#b22222" },
    { title: "青", id: 4, value: "#1e90ff" },
    { title: "紫", id: 5, value: "#800080" },
    { title: "黄", id: 6, value: "#ffd700" },
    { title: "無", id: 7, value: "#f5f5f5" },
  ],
  oshi_colors: [
    { title: "白", id: 1, value: "#c0c0c0" },
    { title: "緑", id: 2, value: "#32cd32" },
    { title: "赤", id: 3, value: "#b22222" },
    { title: "青", id: 4, value: "#1e90ff" },
    { title: "紫", id: 5, value: "#800080" },
  ],
  release_deck: [
    {
      id: 1,
      title: "スタートデッキ「ときのそら&AZKi」",
      name: "スタートデッキ「ときのそら&AZKi」",
    },
    {
      id: 2,
      title: "ブースターパック「ブルーミングレディアンス」",
      name: "ブースターパック「ブルーミングレディアンス」",
    },
    { id: 3, title: "スタートエールセット", name: "スタートエールセット" },
    { id: 4, title: "PRカード", name: "PRカード" },
    {
      id: 5,
      title: "ブースターパック「クインテットスペクトラム」",
      name: "ブースターパック「クインテットスペクトラム」",
    },
    { id: 6, title: "スタートデッキ「赤 百鬼あやめ」", name: "スタートデッキ「赤 百鬼あやめ」" },
    { id: 7, title: "スタートデッキ「青 猫又おかゆ」", name: "スタートデッキ「青 猫又おかゆ」" },
    { id: 8, title: "スタートデッキ「紫 癒月ちょこ」", name: "スタートデッキ「紫 癒月ちょこ」" },
  ],
  support_type: [
    { id: 1, value: "スタッフ", name: "スタッフ" },
    { id: 2, value: "アイテム", name: "アイテム" },
    { id: 3, value: "イベント", name: "イベント" },
    { id: 4, value: "マスコット", name: "マスコット" },
    { id: 5, value: "ツール", name: "ツール" },
    { id: 6, value: "ファン", name: "ファン" },
  ],
  cards: [],
};
